[package]
name = "wasi-env"
version = "0.0.0"
edition = "2021"

[dependencies]
uuid = { version = "1.0.0", features = ["v4"] }
mime_guess = "2.0.4"

[dev-dependencies]
tempfile = "3.1.0"
camino = "1.0.8"
